;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "update-clojure-tools-dependencies-skill")
(def path ".")
(def version "0.1.33")
(def tag "0.1.33")
(def generated-at "2020-07-29T18:48:37Z")
