;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "update-clojure-tools-dependencies-skill")
(def path ".")
(def version "0.1.14")
(def tag "0.1.14")
(def generated-at "2020-05-21T03:16:21Z")
