;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "update-clojure-tools-dependencies-skill")
(def path ".")
(def version "0.1.34")
(def tag "0.1.34")
(def generated-at "2020-11-17T07:47:20Z")
